### ISSUE TITLE
Add grunt tasks to compile individual web components

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/custom-elements#10]
Having to commit the necessary files only after running `grunt` is a nightmare, so the ability to compile individual web components will make life easier, e.g:

`grunt compile:switcher`

**Comment by dgt41** [comment]
haha, we have the options, let me just do something more sensible

**Comment by dgt41** [comment]
https://github.com/joomla-projects/custom-elements/commit/39380daf97f23c2994afde34bcd6adba9543396b should fix it for now
