### ISSUE TITLE
dismiss and auto-dismiss

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-elements#123]
In the alert element
The docs show 
`<joomla-alert type="warning" dismiss="true" auto-dismiss="10000">
`
And I can confirm that works

But that does add a X to close

If I wanted to not have an X then I expected this to work
`<joomla-alert type="warning" auto-dismiss="10000">
`

But it didn't. Is that a bug or intention. Sorry but my js sucks but from what I could understand my code should have worked

**Comment by C-Lodder** [comment]
The `auto-dismiss` feature is inside the `appendButton()` function. That's the issues

**Comment by brianteeman** [comment]
Thanks - now you explained it I can see it ;)

So do I need to create a new function and move that code to the new function?

**Comment by brianteeman** [comment]
thanks - will play tomorrow

**Comment by brianteeman** [comment]
@C-Lodder can you test this code please
https://pastebin.com/aPeHCa60

seems to work but I am coding blind with js

**Comment by C-Lodder** [comment]
@brianteeman Just looked at the code and from what I can see, you're not removing the the element from the DOM when it's closed.

**Comment by brianteeman** [comment]
shucks - back to the drawing board - forgot about the dom

**Comment by C-Lodder** [comment]
@brianteeman Made a couple of tweaks. One of these may work:

1. https://pastebin.com/JVXDZFrf
2. https://pastebin.com/W6a3xMmw

**Comment by brianteeman** [comment]
Both work according to my tests

**Comment by C-Lodder** [comment]
Both work auto and without auto-dismiss?

Is so, best to use the first one.

**Comment by brianteeman** [comment]
see #128
