### ISSUE TITLE
Copying JS files after compile

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/custom-elements#13]
We're currently copying all compiled JS files to the following directories:

> docs/_media/js
> demo/js
> dist/js

Is this really needed? Surely we can just copy them to `dist/js` and then ensure all calls to the JS references this directory

**Comment by dgt41** [comment]
Unfortunately we cannot do that! The reason is that both docs and demo are the endpoints for a server  (the docs is for documentation and demo is just a way to fiddle around easily with the elements). So if we use `../` we fall out of the root of the server and then no script gets loaded
