### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/custom-elements#14]
Let's start deciding on some JS coding standards and try to keep things consistant.

### Variables

Variable chaining may not be needed as I believe the compiler will automatically do this, so can just use:

```
const self   = this;
const foobar = 'something else here';
```

Take not of the indentation here too, so the `=` align (using spaces, **not** tabs)

### Funtions (indentation)

```
foo.foreach(function() {

});
```

- **No** space after `function`
- Space after `()`

### If/else statements

**Good**
```
if (foo === bar) {
    alert('foo');
}
else {
    alert('bar');
}
```

**Bad**
```
if (foo === bar) {
    alert('foo');
} else {
    alert('bar');
}
```

**Bad**
```
if (foo === bar)
{
    alert('foo');
}
else
{
    alert('bar');
}
```

@dgt41 thoughts?

**Comment by dgt41** [comment]
Actually 
```js
if (foo === bar) {
    alert('foo');
}
else {
    alert('bar');
}
```
is BAD
The good one is 
```js
if (foo === bar) {
    alert('foo');
} else {
    alert('bar');
}
```
My proposal to the javascript group was to use the airbnb style guide: https://github.com/airbnb/javascript

**Comment by wilsonge** [comment]
I'd :+1: the airbnb style. I've used that on other projects before. Obviously down to the JS group. But when done can we make sure we document what we are using at https://github.com/joomla/coding-standards/ please :)

**Comment by C-Lodder** [comment]
There is no good or bad in regards to putting the `else` on the same line or new line. My example that stated **good** didn't was basically suggesting which one we should use.

Personally I've always written all my code using Joomla's PHP standards, and only recently started using the following in JS:

```
if (foo === bar) {
    alert('foo');
}
else {
    alert('bar');
}
```
 because I find it easier to read. Your choice, happy to do it the other way if you want

**Comment by dgt41** [comment]
@wilsonge airbnb needs some tweaking for custom elements...

**Comment by C-Lodder** [comment]
https://github.com/joomla-projects/custom-elements/commit/5d4a559e551a3e45af5e01917f1ded63057d2de1
