### ISSUE TITLE
alert.js doesn't respect custom alert types

### ISSUE THREAD

**Issue by ReLater** [joomla-projects/custom-elements#142]
`alert.js` restricts the message types to `['info', 'warning', 'danger', 'success']` and falls back to `info` if a custom type like `anythingelse` is used in

`$app->enqueueMessage('Testing type: anythingelse.', 'anythingelse ');`

Please see also comment https://github.com/joomla/joomla-cms/issues/29926#issuecomment-653560295

If you say that this shouldn't be fixed in JS I'll provide a PHP fix there that brings back classes like `alert-anythingelse` for the `joomla-alert` element.

**Comment by dgrammatiko** [comment]
That's by design, alert accepts **only** these types: `['info', 'warning', 'danger', 'success']`

**Comment by ReLater** [comment]
Then it should be documented as B\C break in Joomla 4.
