### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-elements#157]
joomla-custom-elements has a dependency of bootstrap 4.x

Is that still valid?

I did try to do an update here but there were so many warnings ....

@wilsonge

**Comment by C-Lodder** [comment]
I think it was only used for the Bootstrap Demo page: https://github.com/joomla-projects/custom-elements/blob/master/docs/bootstrap-demo.html#L9

Basically to show the elements were agnostic and work on a BS powered page

**Comment by brianteeman** [comment]
I thought I could but with so many warnings I thought it best if someone familiar with the code looked at it

**Comment by wilsonge** [comment]
Yeah I can either just fix the demo page or https://github.com/joomla-projects/custom-elements/pull/155 will ditch the dependency anyhow (which ever comes first). There’s no direct code dependency

**Comment by dgrammatiko** [comment]
Bootstrap is not a dependency anymore here
