### ISSUE TITLE
joomla-alert close within form, submits the form

### ISSUE THREAD

**Issue by sakiss** [joomla-projects/custom-elements#158]
If you load a joomla-alert element within a form and try to close it, the form will be submitted.

Solution:
In the file:[joomla-alert.js](https://github.com/joomla-projects/custom-elements/blob/master/src/js/alert/alert.js)
replace the 
`closeButton.addEventListener('click', () => {`
with:
```
closeButton.addEventListener('click', (event) => {
            event.preventDefault();
```

**Comment by C-Lodder** [comment]
The script actually needs to be updated to ensure the button has `type="button"`, cause without it, it will be treated as `type="submit"`, and thus submitting the form

**Comment by wilsonge** [comment]
Fix here https://github.com/joomla-projects/custom-elements/pull/159
