### ISSUE TITLE
Activate https://greenkeeper.io

### ISSUE THREAD

**Issue by dgt41** [joomla-projects/custom-elements#29]
This will automagically update the nom dependencies whenever a new compatible version is available.
Someone with admin rights needs to do this

**Comment by dgt41** [comment]
@mbabker or @wilsonge or anyone else with the right permissions

**Comment by mbabker** [comment]
![screen shot 2017-08-31 at 1 58 30 pm](https://user-images.githubusercontent.com/368545/29940351-8cb7dde4-8e54-11e7-9b58-e8fadfc3dd58.png)

**Comment by dgt41** [comment]
few lines below there is a link, clicking that you should be able to select the repo

![screen shot 2017-08-31 at 22 01 43](https://user-images.githubusercontent.com/3889375/29940468-07f39686-8e98-11e7-9816-2856991f9493.png)

**Comment by dgt41** [comment]
the landing page of the link is 
![screen shot 2017-08-31 at 22 03 58](https://user-images.githubusercontent.com/3889375/29940587-6830156a-8e98-11e7-8e6a-51fa717483a4.png)

and at the bottom you should be able to select the custom-elements repo
![screen shot 2017-08-31 at 22 04 08](https://user-images.githubusercontent.com/3889375/29940629-7f272e70-8e98-11e7-8300-8e15a8b605aa.png)

**Comment by dgt41** [comment]
Thanks!

**Comment by mbabker** [comment]
The branch it creates is there and the README updated.  No PR yet though, so hopefully it's doing something.
