### ISSUE TITLE
[Alert] "auto-dismiss" time not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/custom-elements#31]
Setting the auto dismiss time to 10 seconds seems to close the alert instantly.

**Comment by dgt41** [comment]
what is the html markup that you used?

**Comment by C-Lodder** [comment]
Just happens on the docs: https://joomla-projects.github.io/custom-elements/#/alert

Look at the warning alert.

**Comment by C-Lodder** [comment]
fixed: https://github.com/joomla-projects/custom-elements/commit/4b2c345435fd2647f2b679daa7039b2f8341e56a
