### ISSUE TITLE
[Alert] Add option to "float"

### ISSUE THREAD

**Issue by C-Lodder** [joomla-projects/custom-elements#34]
Ad the following attribute options

- **float**
-- _possible values_:
--- false (default)
--- true

- **position**
-- _possible values_:
--- top-left
--- top-center
--- top-right
--- bottom-left
--- bottom-center
--- bottom-right

**Comment by dgt41** [comment]
One option is better 

- float
-- possible values:
--- top-left
--- top-center
--- top-right
--- bottom-left
--- bottom-center
--- bottom-right

**Comment by C-Lodder** [comment]
ah yes, good point

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla-projects/custom-elements/pull/38
