### ISSUE TITLE
Remove getText method

### ISSUE THREAD

**Issue by dgt41** [joomla-projects/custom-elements#46]
https://github.com/joomla-projects/custom-elements/blob/9002bce60943942bf71f5eb51a3ea6b054cde378/src/js/alert/alert.js#L176

This makes components Joomla specific, also is not needed as we can pass the strings through attributes. Lets fix that...

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla-projects/custom-elements/pull/51
