### ISSUE TITLE
Fix the sauce labs no session thing

### ISSUE THREAD

**Issue by dgt41** [joomla-projects/custom-elements#57]
Tests pass (probably the ES5) and then everything stalls ![screen shot 2017-09-07 at 13 07 17](https://user-images.githubusercontent.com/3889375/30158329-98d2d5a6-93cd-11e7-8e33-ce3f1d37febc.png)

**Comment by dgt41** [comment]
It's not the es5/es6 part: 
![screen shot 2017-09-07 at 13 20 47](https://user-images.githubusercontent.com/3889375/30158921-82408c96-93cf-11e7-8728-6104960416ab.png)

Also I have no clue why the session get's broken

**Comment by C-Lodder** [comment]
Why is it testing on FF 50?

Latest version is 55 and I think Chrome should be 60

**Comment by dgt41** [comment]
I have no clue: 
![screen shot 2017-09-07 at 13 32 18](https://user-images.githubusercontent.com/3889375/30159358-00b948a0-93d1-11e7-93cb-af987142dfc7.png)
![screen shot 2017-09-07 at 13 31 11](https://user-images.githubusercontent.com/3889375/30159327-e300ac72-93d0-11e7-8e96-cc7747b1fe58.png)

**Comment by C-Lodder** [comment]
Updated browser versions: https://github.com/joomla-projects/custom-elements/pull/58
