### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-elements#98]
The latest release is 0.0.25 but there have been fixes since then. Please can a new release be made and then this updated https://github.com/joomla/joomla-cms/blob/4.0-dev/package.json#L37 so that the cms is using the corrected files

**Comment by brianteeman** [comment]
@wilsonge tagging you as I don't know who has the required access to do this

**Comment by wilsonge** [comment]
Dimitris left the pw for it in the vault. i'll get this sorted out the next few days :)

**Comment by wilsonge** [comment]
New release done and also updated it into the CMS
